//! Risk confirmation modal: per-item explanation tuned to category + risk level.

use crate::scanner::system_cleaner::{CleanCategory, CleanRisk};
use crate::tui::model::*;
use crate::tui::styles::*;
use crate::utils::fs::format_size;
use ratatui::prelude::*;
use ratatui::widgets::*;

pub fn render_risk_confirm(frame: &mut Frame, area: Rect, model: &SystemCleanerModel) {
    let item = match model.items.get(model.cursor) {
        Some(i) => i,
        None => return,
    };

    let modal_area = center_modal(frame, area, 65, 16);
    let border_color = match item.risk {
        CleanRisk::Safe => GREEN,
        CleanRisk::Caution => YELLOW,
        CleanRisk::Danger => RED,
    };

    let block = Block::default()
        .borders(Borders::ALL)
        .border_type(BorderType::Thick)
        .border_style(Style::default().fg(border_color))
        .style(Style::default().bg(MODAL_BG));
    let inner = block.inner(modal_area);
    frame.render_widget(block, modal_area);

    let risk_label = match item.risk {
        CleanRisk::Safe => "SAFE TO CLEAN",
        CleanRisk::Caution => "CAUTION",
        CleanRisk::Danger => "DANGER",
    };

    let explanation = risk_explanation(&item.risk, &item.category);

    let mut lines = vec![
        Line::from(Span::styled(
            format!(" {} ", risk_label),
            Style::default().fg(WHITE).bg(border_color).bold(),
        )),
        Line::from(""),
        Line::from(vec![
            Span::styled("  Item: ", Style::default().fg(PURPLE)),
            Span::styled(&item.name, Style::default().fg(WHITE).bold()),
        ]),
        Line::from(vec![
            Span::styled("  Size: ", Style::default().fg(PURPLE)),
            Span::styled(format_size(item.size), Style::default().fg(YELLOW)),
        ]),
        Line::from(""),
    ];

    for exp in &explanation {
        lines.push(Line::from(Span::styled(
            format!("  {}", exp),
            Style::default().fg(GRAY),
        )));
    }

    lines.push(Line::from(""));
    lines.push(Line::from(Span::styled(
        "  Proceed? (y/N)",
        Style::default().fg(WHITE),
    )));

    frame.render_widget(Paragraph::new(lines).alignment(Alignment::Left), inner);
}

fn risk_explanation(risk: &CleanRisk, category: &CleanCategory) -> Vec<&'static str> {
    match (risk, category) {
        (CleanRisk::Danger, _) => vec![
            "This app is currently running.",
            "Cleaning while running may cause crashes or data loss.",
            "Close the app first, then retry.",
        ],
        (CleanRisk::Caution, CleanCategory::Docker) => vec![
            "Docker images/containers will need to be re-pulled.",
            "Build cache will be rebuilt on next docker build.",
            "This may take significant time on slow connections.",
        ],
        (CleanRisk::Caution, CleanCategory::VMs) => vec![
            "Virtual machine data may be permanently deleted.",
            "Emulator AVDs will need to be recreated.",
            "Docker VM disk will be rebuilt on restart.",
        ],
        (CleanRisk::Caution, CleanCategory::Cache) => vec![
            "Cache will be rebuilt automatically on next use.",
            "First build after cleaning may be slower.",
            "No permanent data will be lost.",
        ],
        (CleanRisk::Safe, CleanCategory::Cache) => vec![
            "This cache is rebuilt automatically on next use.",
            "No projects or data will be affected.",
            "Disk space will be freed immediately.",
        ],
        (CleanRisk::Safe, CleanCategory::Logs) => vec![
            "Old log files older than 7 days.",
            "These are regenerated by their apps automatically.",
            "No data or functionality will be lost.",
        ],
        (CleanRisk::Safe, CleanCategory::Downloads) => vec![
            "Large installer files (ISO, DMG, PKG).",
            "These are typically no longer needed after installation.",
            "Re-download from the original source if needed.",
        ],
        (CleanRisk::Safe, CleanCategory::VMs) => vec![
            "Legacy VM data no longer in active use.",
            "Safe to remove if you no longer use this tool.",
        ],
        _ => vec![
            "This item can be safely removed.",
            "It will be rebuilt automatically if needed.",
        ],
    }
}
